services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsights
    ports:
      - "5540:5540"
